### ISSUE TITLE
Off centered companies list

### ISSUE THREAD

**Issue by jazzjacob** [Systemvetardagen/systemvetardagen.se#309] opened 2024-02-07 13:34 UTC
Centering seems to disappear on window widths

<img width="1680" alt="Screenshot 2024-02-07 at 14 33 02" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/80760206/3cf8137d-583a-434e-aff7-d2372978a259">

**Comment by olehoef** [comment] 2024-02-07 13:50
can't really reproduce. Which monitor dimensions are you using?

**Comment by R3Kr** [comment] 2024-02-07 15:44
![image](https://github.com/Systemvetardagen/systemvetardagen.se/assets/76439773/0d8992d7-e549-4485-8ff9-651ad7a2fd6c)
same, 1920 x 1080. chrome

**Comment by amirhossein-haerian** [comment] 2024-02-07 17:50
the problem is now fixed on the off-centered-companies branch

**Closed** 2024-02-08 11:11 UTC
Labels: bug, catalog
