### ISSUE TITLE
Hide partner content if not partner

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#298] opened 2024-02-07 09:16 UTC
If a company has uploaded partner content and later the partner option is unchecked, the partner content is still displayed. Either we stop sending the content from the cms or we add a v-if on the partner content component.

<img width="778" alt="Screenshot 2024-02-07 at 09 32 42" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/8548225a-74c5-488b-ab31-f0c321b248fb">

**Comment by amirhossein-haerian** [comment] 2024-02-07 12:27
The issue is now fixed inside the not_sposnsor_issue branch.
However, Scania is not a sponsor now. We have some data on Scania as a sponsor, and it seems that the sponsor status was active for it, and some data has been added related to being a sponsor for Scania. now the code is fixed for this situation, and it will check for being a sponsor or not before showing data of youtube link and extra text.

**Closed** 2024-02-08 10:46 UTC
Labels: bug, High priority, Company Page
