### ISSUE TITLE
Hide match list headings if no tags present

### ISSUE THREAD

**Issue by olehoef** [Systemvetardagen/systemvetardagen.se#297] opened 2024-02-07 09:14 UTC
It would look nicer if the headings wouldn't show if there are no tags.

<img width="863" alt="Screenshot 2024-02-07 at 09 32 17" src="https://github.com/Systemvetardagen/systemvetardagen.se/assets/81076759/ba487b8a-c74a-4f45-939f-787944f684b9">

**Comment by amirhossein-haerian** [comment] 2024-02-07 12:42
The issue is now fixed inside the no_tags_issue branch.

**Closed** 2024-02-07 13:20 UTC
Labels: Medium priority, Design, Company Page
